apiVersion: v1
kind: ConfigMap
metadata:
  name: poem-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Poem</title>
        <style>
          body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        </style>
    </head>
    <body>
        <h1>ğŸ¶</h1>
        <pre>
        "Letâ€™s playâ€”heads or tails? 
        Head woofing or tail wagging,
        winner gets itâ€”love."  
        </pre>
    </body>
    </html>